version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: think_eye
    ports:
      - 3306:3306